# Generated by Django 4.2.1 on 2024-01-30 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SetSending', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='время последней попытки')),
                ('status', models.SmallIntegerField(default=0, verbose_name='статус попытки')),
                ('description', models.TextField(blank=True, null=True, verbose_name='ответ почтового сервера')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SetSending.setsending', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Log',
            },
        ),
    ]
