# Generated by Django 4.2.1 on 2024-01-29 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetSending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField(verbose_name='время начала рассылки')),
                ('interval', models.PositiveIntegerField(default=0, verbose_name='интервал рассылки в секундах')),
                ('time_end', models.DateTimeField(verbose_name='время окончания рассылки')),
                ('status', models.PositiveSmallIntegerField(default=1, verbose_name='статус рассылки')),
                ('list_address', models.CharField(verbose_name='список адресов')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.message', verbose_name='сообщение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройка рассылки',
                'verbose_name_plural': 'Настройки рассылки',
            },
        ),
    ]
